config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#index'

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  get 'users/index', :to => 'users#index', :as => 'user_index'
  post 'users/subscribe', :to => 'users#subscribe', :as => 'user_subscribe'
  post 'users/unsubscribe', :to => 'users#unsubscribe', :as => 'user_unsubscribe'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :database_authenticatable, :rememberable, :validatable
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable, :recoverable
  devise :trackable, :omniauthable, :omniauth_providers => [:twitter]

   # validation
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A[A-Za-z0-9]+\z/i
  # Validation for attributes
  validates :username, :uniqueness => true, :presence => true
  #validates :email, :presence => true, :length => { :maximum => 128 }

  enum plan: { free: 0, premium: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #https://github.com/plataformatec/devise/wiki/OmniAuth%3A-Overview

  # when there is only omniauth, no normal signup/login
  def new_session_path(scope)
    new_user_session_path
  end

  # path to redirect user after sign in
  def after_sign_in_path_for(resource)
    user_index_path
  end

  # Require user login
  def require_login
    if !user_signed_in?
      #redirect_to user_login_path
      redirect_to root_path
    end
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    #@user = User.from_omniauth(request.env["omniauth.auth"])
    #
    #if @user.persisted?
    #  sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    #  set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    #else
    #  session["devise.facebook_data"] = request.env["omniauth.auth"]
    #  redirect_to new_user_registration_url
    #end
    puts "le oauth info"
    puts  request.env["omniauth.auth"]

    provider = request.env["omniauth.auth"]["provider"]
    uid = request.env["omniauth.auth"]["uid"]
    access_token = request.env["omniauth.auth"]["credentials"]["token"]
    username = request.env["omniauth.auth"]["info"]["nickname"]

    puts "provider is #{provider}"
    puts "uid is #{uid}"
    puts "access token is #{access_token}"
    puts "username is #{username}"

    @user = User.where(:uid => uid).take

    if !@user
        @user = User.create(:oauth_token => access_token, :uid => uid, :provider => provider, :username => username)
    else
        @user.oauth_token = access_token
        @user.save
    end

    sign_in_and_redirect @user, :event => :authentication
    flash[:success] = "Login success"
    #set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?

    #redirect_to root_path
  end

  def failure
    flash[:danger] = "Twitter login error"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  
  def index
    @client_token = Braintree::ClientToken.generate
  end

  def subscribe
    payment_method_nonce = params[:payment_method_nonce]

    # find if existing customer id (twitter id) exist
    begin
      customer = Braintree::Customer.find(current_user.uid)
    rescue Braintree::NotFoundError => e
      # create a customer
      customer = Braintree::Customer.create(
        :id => current_user.uid,
        :payment_method_nonce => payment_method_nonce
      )
    rescue StandardError => e
      # other exceptions
      puts e.message
      flash[:danger] = "Something wrong with payment gateway, rest assured you are not charged."
    ensure
      # always be executed
      if !customer.id.blank?
        payment_method = customer.payment_methods[0]

        result = Braintree::Subscription.create(
          :payment_method_token => payment_method.token,
          :plan_id => "premium"
        )

        if result.success?
          current_user.plan = "premium"
          current_user.subscription_id = result.subscription.id
          current_user.billing_day_of_month = result.subscription.billing_day_of_month
          current_user.save

          flash[:success] = "You have subscribed to the premium plan! Congratulation on gaining higher social status!"
        end

      else
        #p customer.errors
      end

    end

    


    redirect_to user_index_path
  end

  def unsubscribe
    #result = Braintree::Customer.delete(current_user.uid)
    result = Braintree::Subscription.cancel(current_user.subscription_id)
    if result.success?
      puts "customer successfully deleted"
      current_user.plan = "free"
      current_user.subscription_id = nil
      current_user.billing_day_of_month = nil
      current_user.save

      flash[:success] = "You have unsubscribed, welcome back peasant."
    else
      p result.errors
    end

    redirect_to user_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Statuus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://use.typekit.net/qvt7dlj.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
  </head>

  <body>
    <div class="container">
      <br><br>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 text-center">
    <br>
    <span class="title">User panel</span><br>
    <span> Hi, <%= current_user.username %> </span>
    <% if current_user.premium? %>
      <span class="premium-badge">premium</span>
    <% end %>
    <br><br>
    <% if current_user.plan == 'free' %>
      <%= form_tag user_subscribe_path, :id => 'checkout' do %>
        <div id="payment-form"></div>
        <input type="submit" class="btn btn-primary btn-lg" value="Subscribe premium for $2.99 a month">
      <% end %>
      
      <script src="https://js.braintreegateway.com/js/braintree-2.29.0.min.js"></script>
      <script>
        // We generated a client token for you so you can test out this code
        // immediately. In a production-ready integration, you will need to
        // generate a client token on your server (see section below).
        var clientToken = "<%= @client_token %>";
      
        braintree.setup(clientToken, "dropin", {
          container: "payment-form"
        });
      </script>
    <% else %>
      <%= form_tag user_unsubscribe_path do %>
         <input type="submit" class="btn btn-warning btn-lg" value="Unsubscribe and become a peasant">
      <% end %>
    <% end %>
    <br><br>
    <a href="<%= destroy_user_session_path %>" class="btn btn-success">Logout</a>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>